[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.mbstring", "php84Extensions.pdo", "php84Extensions.tokenizer", "php84Extensions.xml"]

[start]
cmd = "frankenphp run --config /app/Caddyfile"